### ISSUE TITLE
library declaration in ansible.cfg

### ISSUE THREAD

**Issue by rogerscuall** [network-automation/ansible_inventory_report#2]
The library is set to a path to napalm in the ansible.cfg, is this needed? I was able to run this successfully without napalm installed.

**Comment by IPvSean** [comment]
no this is leftover from my NAPLAM examples, I just kept re-using the same ansible.cfg, I will go ahead and fix this, thanks for bringing it to my attention.

**Comment by IPvSean** [comment]
removed with https://github.com/network-automation/ansible_inventory_report/commit/d8d2b8b06fecff2503dc82675c92739e2f2ae9e1
